const {
  SCRIPT_SRC,
  DATABASE_URL,
  MODULE_ADDRESS,
  COIN_ADDRESS,
  PRICE_FEEDER_ADDRESS,
  PRICE_FEED_AND_SYNCER_PK,
  APT_FEEDER_ADDRESS,
  USDT_FEEDER_ADDRESS,
  USDC_FEEDER_ADDRESS,
  BTC_FEEDER_ADDRESS,
  ETH_FEEDER_ADDRESS,
  BNB_FEEDER_ADDRESS,
  SOL_FEEDER_ADDRESS,
  AVAX_FEEDER_ADDRESS,
  PEPE_FEEDER_ADDRESS,
  DOGE_FEEDER_ADDRESS,
  STAPT_FEEDER_ADDRESS,
  EXECUTER_PK_1,
  LIQUIDATOR_PK,
  TELEGRAM_TOKEN,
} = require("./ecosystem_base");

module.exports = {
  apps: [
    {
      name: "agdex-price-feeder",
      script: SCRIPT_SRC,
      watch: true,
      env: {
        PORT: 3000,
        DATABASE_URL: DATABASE_URL,
        MODULE_ADDRESS: MODULE_ADDRESS,
        COIN_ADDRESS: COIN_ADDRESS,

        PRICE_FEEDER_ADDRESS: PRICE_FEEDER_ADDRESS,
        APT_FEEDER_ADDRESS: APT_FEEDER_ADDRESS,
        USDT_FEEDER_ADDRESS: USDT_FEEDER_ADDRESS,
        USDC_FEEDER_ADDRESS: USDC_FEEDER_ADDRESS,
        BTC_FEEDER_ADDRESS: BTC_FEEDER_ADDRESS,
        ETH_FEEDER_ADDRESS: ETH_FEEDER_ADDRESS,
        BNB_FEEDER_ADDRESS: BNB_FEEDER_ADDRESS,
        SOL_FEEDER_ADDRESS: SOL_FEEDER_ADDRESS,
        AVAX_FEEDER_ADDRESS: AVAX_FEEDER_ADDRESS,
        PEPE_FEEDER_ADDRESS: PEPE_FEEDER_ADDRESS,
        DOGE_FEEDER_ADDRESS: DOGE_FEEDER_ADDRESS,
        STAPT_FEEDER_ADDRESS: STAPT_FEEDER_ADDRESS,
        TELEGRAM_TOKEN: TELEGRAM_TOKEN,
        //private keys
        PRICE_FEED_AND_SYNCER_PK: PRICE_FEED_AND_SYNCER_PK,
        EXECUTER_PK: EXECUTER_PK_1,
        LIQUIDATOR_PK: LIQUIDATOR_PK,

        //sync func
        SYNC_POSITIONS: "ON",
        SYNC_ORDERS: "ON",
        SYNC_VAULT_CONFIG: "OFF",
        SYNC_LP_TOKEN_PRICE: "OFF",
        //new feature
        SYNC_SIMULATE_LP: "ON",
        SYNC_REFERRER: "ON",
        //campaign events
        SYNC_CAMPAIGN_EVENTS: "OFF",

        //onchain func
        UPDATE_PRICE_FEED: "ON",
        EXECUTE_ORDERS: "OFF",
        EXECUTE_LIQUIDATION: "OFF",

        //vault switcher
        VAULT_APT: "ON",
        VAULT_USDC: "OFF",
        VAULT_USDT: "OFF",
        VAULT_BTC: "ON",
        VAULT_ETH: "ON",
        VAULT_STAPT: "ON",

        //clear
        CLEAR_PRICE_DATA: "ON",

        //test
        BATCH_TEST: "OFF",

        //telegram
        TELEGRAM_BOT: "ON",
      },
    },
    {
      name: "agdex-scanner",
      script: SCRIPT_SRC,
      watch: true,
      env: {
        PORT: 3001,

        DATABASE_URL: DATABASE_URL,
        MODULE_ADDRESS: MODULE_ADDRESS,
        COIN_ADDRESS: COIN_ADDRESS,

        PRICE_FEEDER_ADDRESS: PRICE_FEEDER_ADDRESS,
        APT_FEEDER_ADDRESS: APT_FEEDER_ADDRESS,
        USDT_FEEDER_ADDRESS: USDT_FEEDER_ADDRESS,
        USDC_FEEDER_ADDRESS: USDC_FEEDER_ADDRESS,
        BTC_FEEDER_ADDRESS: BTC_FEEDER_ADDRESS,
        ETH_FEEDER_ADDRESS: ETH_FEEDER_ADDRESS,
        BNB_FEEDER_ADDRESS: BNB_FEEDER_ADDRESS,
        SOL_FEEDER_ADDRESS: SOL_FEEDER_ADDRESS,
        AVAX_FEEDER_ADDRESS: AVAX_FEEDER_ADDRESS,
        PEPE_FEEDER_ADDRESS: PEPE_FEEDER_ADDRESS,
        DOGE_FEEDER_ADDRESS: DOGE_FEEDER_ADDRESS,
        STAPT_FEEDER_ADDRESS: STAPT_FEEDER_ADDRESS,
        TELEGRAM_TOKEN: TELEGRAM_TOKEN,

        //private keys
        PRICE_FEED_AND_SYNCER_PK: PRICE_FEED_AND_SYNCER_PK,
        EXECUTER_PK: EXECUTER_PK_1,
        LIQUIDATOR_PK: LIQUIDATOR_PK,

        //sync func
        SYNC_POSITIONS: "ON",
        SYNC_ORDERS: "ON",
        SYNC_VAULT_CONFIG: "ON",
        SYNC_LP_TOKEN_PRICE: "ON",
        //new feature
        SYNC_SIMULATE_LP: "OFF",
        SYNC_REFERRER: "OFF",
        //campaign events
        SYNC_CAMPAIGN_EVENTS: "ON",

        //onchain func
        UPDATE_PRICE_FEED: "OFF",
        EXECUTE_ORDERS: "OFF",
        EXECUTE_LIQUIDATION: "OFF",

        //vault switcher
        VAULT_APT: "OFF",
        VAULT_USDC: "ON",
        VAULT_USDT: "ON",
        VAULT_BTC: "OFF",
        VAULT_ETH: "OFF",
        VAULT_STAPT: "OFF",
        //clear
        CLEAR_PRICE_DATA: "OFF",

        //test
        BATCH_TEST: "OFF",

        //telegram
        TELEGRAM_BOT: "OFF",
      },
    },
  ],
};
